# Generated by Django 4.2.17 on 2024-12-21 17:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='The branch this course belongs to.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='users.branch'),
        ),
        migrations.AddField(
            model_name='course',
            name='enrolled_users',
            field=models.ManyToManyField(blank=True, help_text='The learners enrolled in this course.', limit_choices_to={'role': 'learner'}, related_name='enrolled_courses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, help_text='The instructor assigned to this course.', limit_choices_to={'role': 'instructor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructor_courses', to=settings.AUTH_USER_MODEL),
        ),
    ]
