# Generated by Django 4.2.17 on 2024-12-22 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_scorm_runtime_tracking_alter_course_content_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scorm',
            name='completion_status',
            field=models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_started', help_text='The current completion status of the SCORM package.', max_length=20),
        ),
        migrations.AddField(
            model_name='scorm',
            name='last_accessed',
            field=models.DateTimeField(auto_now=True, help_text='The timestamp for the last access of the SCORM package.'),
        ),
        migrations.AddField(
            model_name='scorm',
            name='score',
            field=models.IntegerField(blank=True, help_text='The score returned from the SCORM package (if applicable).', null=True),
        ),
        migrations.AddField(
            model_name='scorm',
            name='time_spent',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Total time spent by the learner in hours.', max_digits=5),
        ),
    ]
